# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python pytest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # since * is a special character in YAML you have to quote this string
    - cron:  '0 22 1/7 * *'

jobs:
  default:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, ]
        tf-version: [2.5.3, 2.6.4, 2.7.4, 2.8.4, 2.9.3]
        include:
          - python-version: "3.10"
            tf-version: "2.10"
          - python-version: "3.10"
            tf-version: "2.11"
          - python-version: 3.8
            tf-version: 2.3.1
          - python-version: 3.8
            tf-version: 2.4.2

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: System informations
      run: |
        uname -a
        free -g
        pwd
    - name: Install dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        pip install tensorflow==${{ matrix.tf-version }} "numpy<1.24.0"
        pip install git+https://github.com/DataCanvasIO/Hypernets
        pip install -r requirements.txt "protobuf<4.0" "numpy<1.24.0"
        pip install pytest-cov==2.4.0  python-coveralls  codacy-coverage
        pip list
    - name: Test with pytest
      run: |
        pytest --cov=deeptables --durations=30 -k "not dask and not batch_trainer"

  py36_37:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.6]
        tf-version: [2.1.0, 2.2.0, 2.3.1, 2.4.2]
#        exclude:
#          - tf-version: 2.1.0
#            python-version: 3.8
#          - tf-version: 2.2.0
#            python-version: 3.8

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: System informations
      run: |
        uname -a
        free -g
        pwd
    - name: Install dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        pip install tensorflow==${{ matrix.tf-version }}
        pip install git+https://github.com/DataCanvasIO/Hypernets
        pip install -r requirements.txt "protobuf<4.0" "numpy==1.19.5" "featuretools<=0.27" "h5py==2.10.0"
        pip install pytest-cov==2.4.0  python-coveralls  codacy-coverage
        pip list
    - name: Test with pytest
      run: |
        pytest --cov=deeptables --durations=30 -k "not dask and not batch_trainer"
